# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 17:28
from __future__ import unicode_literals

import Tagent1.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True, validators=[Tagent1.validators.validate_city])),
                ('state', models.CharField(blank=True, max_length=20, null=True, validators=[Tagent1.validators.validate_state])),
                ('landmark', models.CharField(blank=True, max_length=20, null=True, validators=[Tagent1.validators.validate_landmark])),
                ('pincode', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15, validators=[Tagent1.validators.validate_mobile_no])),
                ('phone_number', models.CharField(max_length=15, validators=[Tagent1.validators.validate_phone_no])),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('contactinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Tagent1.ContactInfo')),
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20, validators=[Tagent1.validators.validate_first_name])),
                ('last_name', models.CharField(max_length=20, validators=[Tagent1.validators.validate_last_name])),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=50, validators=[Tagent1.validators.validate_education])),
                ('company_name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=100, validators=[Tagent1.validators.validate_specelization])),
                ('experence', models.IntegerField()),
                ('agent_notes', models.TextField()),
                ('address', models.ManyToManyField(to='Tagent1.Address')),
            ],
            bases=('Tagent1.contactinfo',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('contactinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Tagent1.ContactInfo')),
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.ManyToManyField(blank=True, null=True, to='Tagent1.Address')),
            ],
            bases=('Tagent1.contactinfo',),
        ),
    ]
